language: node_js
node_js:
- 5.6
before_script:
- gem install percy-cli
after_success:
- '[ "$TRAVIS_SECURE_ENV_VARS" = "true" ] && npm run perceptual-diff'
sudo: false
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: TCVnWEg+u1GCclhilINDHRrdxntFB454cfaipNY1snVI7veYveQxJpc1G0PsM+2mlEOqZX+mVFgZBMYUaVDXutWvntDL8PNWavU8zzxn94CUExgEOkbbYTM9WxhPZz/bhWtxdmTO1vvCT89MPzSw4/YZlhIfiU9OGU5LNvwvLFY=
  on:
    tags: true
    repo: Brightspace/valence-ui-link
env:
  global:
    secure: bil9iZPlfnF6350dkkGSHE3mzON2wPTSwKP9mYnWkKCcyuPXNSyCRIBwHDwLvxRRr+Bkr0/6tpJkZiJYktt6BZMMQHSvAJ3JjnLz5emPt8IqeH8U/EmHHPu/kX7Lq445x5VIRaEUj1WKAkjyOqZyHj21mJXTZFx8pK2our5PYS4=
