language: node_js
node_js: stable
script:
- polylint
- wct --skip-plugin local
addons:
  sauce_connect: true
  jwt:
    # SAUCE_ACCESS_KEY
    secure: Gvu/Z4MhLq5kmhWcnDWfJ/CyAuA4aR3Rkz5bgnbd1Z0V41200vPdcUv32s2KgMlJt3zwMRACIAwYxZu7N1K+eh1LD4fq7LednNlQ4FNlWMLybmB7G7ze1tUjt5ESVYK04RI9mm9qyNSC1ao6pRXO0UPf3z6KgwPl8QAZDJldIF4=
env:
  global:
    # SAUCE_USERNAME
    secure: CkvZ9UNWh9n12jFC6CDg7bTCp9XbQ6Fsrow3xafvrz7cKbsVUnpj5fvSq0YtkiDe2thyIBfUKrvC+BdWbZBs5t1KqsxQVXMpDzcJPXvV2GdIET0dzM1buzOfIHBznFUuXZbhUcp0nDRbMiWK6jAaYuyXX4wU8zMJ8rWtS9ZMUPI=
